version: "3.8"
services:
    user_management_service:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            DB_HOST: db
            DB_POST: 5332
            DB_DATABASE: user_management
            DB_USERNAME: admin
            DB_PASSWORD: pass
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: user_management
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
